Ever since learning about Einstein summation notation a couple of years ago (in 2020), I have been fascinated by it.

[INSERT Einstein quote about simplyfing math]

[INSERT quick recap of rules here]

So when I learned about `numpy`’s `einsum` function, I knew that the time would come when I would like to apply it. This blog post is here to discuss my use case.

# Quick intro to `np.einsum`

In [18]:
import numpy as np

vec_a = np.arange(5)

vec_b = np.arange(5) + 4

mat_A = vec_a[:, None] @ vec_b[:, None].T

In [19]:
mat_A

array([[ 0,  0,  0,  0,  0],
       [ 4,  5,  6,  7,  8],
       [ 8, 10, 12, 14, 16],
       [12, 15, 18, 21, 24],
       [16, 20, 24, 28, 32]])

In [11]:
np.einsum('i,j', vec_a, vec_b)

array([[ 0,  0,  0,  0,  0],
       [ 4,  5,  6,  7,  8],
       [ 8, 10, 12, 14, 16],
       [12, 15, 18, 21, 24],
       [16, 20, 24, 28, 32]])

We can also specify (explicit mode) on which indices the summation should occur with `->`.

In [23]:
np.einsum('i,j->i', vec_a, vec_b)

array([  0,  30,  60,  90, 120])

Here, this sums on index j, leaving one free index i. So the indices after the `->` are the free ones and the others are eliminated.

In [13]:
np.einsum('i,j->j', vec_a, vec_b)

array([40, 50, 60, 70, 80])

Then, there is the repeating of indices.

In [27]:
np.einsum('ii', mat_A) # sums on diagonal

np.int64(70)

In [28]:
np.trace(mat_A)

np.int64(70)

In [30]:
np.einsum('ij->j', mat_A)

array([40, 50, 60, 70, 80])